version: "3.3"
services:
  mysql:
    container_name: mysql
    image: mysql:latest
    ports:
    - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 'database'
      MYSQL_DATABASE: 'team_way_work_planning'
    # TODO add volume to persist data. 
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  laravel:
    build:
      context: .
      dockerfile: laravel-docker/Dockerfile
    container_name: laravel
    ports:
    - 8000:8000
    networks:
      - app-network

    depends_on:
      mysql:
        condition: service_healthy


networks:
  app-network:
    driver: bridge
